import 'package:picktory/models/community_comment.dart';
import 'package:picktory/models/community_post.dart';
import 'package:picktory/models/user_mission.dart';

class DummyCommunityData {
  static final List<CommunityPost> posts = [
    const CommunityPost(
      id: 'post-1',
      authorNickname: '예능러버88',
      authorBadge: '미션마스터',
      programLabel: '환승연애4 · 5화',
      title: '5화 마지막 커플 예측 정리',
      content: '저는 수지&현준 조합이 제일 자연스러웠어요. 다들 픽 공유해요!',
      likeCount: 42,
      commentCount: 9,
      viewCount: 1204,
      createdAtLabel: '2시간 전',
      isMine: false,
    ),
    const CommunityPost(
      id: 'post-2',
      authorNickname: '강아지#123',
      authorBadge: '미션마스터',
      programLabel: '환승연애4 · 5화',
      title: '공유한 미션: 5화 마지막 커플',
      content: '미션 결과 기다리는 중입니다. A vs B 고민돼요.',
      likeCount: 18,
      commentCount: 3,
      viewCount: 532,
      createdAtLabel: '5시간 전',
      isMine: true,
      isMissionShare: true,
      linkedMissionLabel: '5화 마지막 커플 →',
      linkedMissionId: 'mission-hero-1',
    ),
    const CommunityPost(
      id: 'post-3',
      authorNickname: '익명',
      programLabel: '나는솔로 · 10기',
      title: '10기 최종 커플 라인업',
      content: '개인적으로 2호 커플이 우승할 것 같아요.',
      likeCount: 7,
      commentCount: 1,
      viewCount: 210,
      createdAtLabel: '어제',
      isMine: false,
      isAnonymous: true,
    ),
  ];

  static final Map<String, List<CommunityComment>> commentsByPost = {
    'post-1': [
      const CommunityComment(
        id: 'cmt-1',
        postId: 'post-1',
        authorNickname: '예능러버88',
        content: '저도 수지 선택했어요! 맞길...',
        createdAtLabel: '1시간 전',
        likeCount: 3,
        isMine: false,
      ),
      const CommunityComment(
        id: 'cmt-2',
        postId: 'post-1',
        authorNickname: '강아지#123',
        content: '현준 라인 설득력 있네요',
        createdAtLabel: '30분 전',
        likeCount: 1,
        isMine: true,
      ),
    ],
    'post-2': [
      const CommunityComment(
        id: 'cmt-3',
        postId: 'post-2',
        authorNickname: '강아지#123',
        content: '결과 나오면 공유할게요',
        createdAtLabel: '3시간 전',
        likeCount: 0,
        isMine: true,
      ),
    ],
  };

  static final List<UserMission> userMissions = [
    const UserMission(
      id: 'um-1',
      type: UserMissionType.mission,
      title: '5화 엔딩 커플 최종 픽',
      authorNickname: '미션마스터',
      authorBadge: '미션마스터',
      programLabel: '환승연애4 · 5화',
      status: UserMissionStatus.active,
      remainingLabel: '02:34:12 남음',
      pointCost: 50,
      likeCount: 42,
      commentCount: 9,
      viewCount: 820,
      participantCount: 234,
      createdAtLabel: '3시간 전',
      isMine: false,
      choices: ['A. 수지 & 현준', 'B. 민아 & 재훈'],
      description: '👤 유저가 만든 미션 · 부적절한 내용은 신고',
    ),
    const UserMission(
      id: 'um-2',
      type: UserMissionType.poll,
      title: '오늘 방송 최고 명장면은?',
      authorNickname: '픽덕후',
      programLabel: '나는솔로 · 10기',
      status: UserMissionStatus.active,
      likeCount: 28,
      commentCount: 9,
      viewCount: 410,
      participantCount: 156,
      createdAtLabel: '6시간 전',
      isMine: true,
      choices: ['A. 첫만남', 'B. 데이트'],
      description: '👤 유저가 만든 투표 · 부적절 내용 신고',
    ),
    const UserMission(
      id: 'um-3',
      type: UserMissionType.mission,
      title: '중간 탈락자 예측',
      authorNickname: '강아지#123',
      programLabel: '프로듀스101 · 6화',
      status: UserMissionStatus.closed,
      remainingLabel: '마감',
      pointCost: 30,
      likeCount: 11,
      commentCount: 2,
      viewCount: 190,
      participantCount: 88,
      createdAtLabel: '2일 전',
      isMine: true,
      choices: ['A. 김하준', 'B. 박서진'],
    ),
  ];
}
